name = "ZarrDatasets"
uuid = "519a4cdf-1362-424a-9ea1-b1d782dbb24b"
authors = ["Alexander Barth <barth.alexander@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CommonDataModel = "1fbeeb36-5f17-413c-809b-666fb144f157"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Zarr = "0a941bbe-ad1d-11e8-39d9-ab76183a1d99"

[compat]
julia = "1"
CommonDataModel = "0.3.4"
DataStructures = "0.17, 0.18"
Zarr = "0.9.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
